/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusDetails {
  'verified' : boolean,
  'operator' : string,
  'ticketReference' : [] | [string],
  'seatNumber' : bigint,
}
export interface CarDetails { 'verified' : boolean, 'registration' : string }
export type Conditional = { 'onFlight' : FlightDetails } |
  { 'onBus' : BusDetails } |
  { 'onCar' : CarDetails } |
  { 'onTrain' : TrainDetails };
export type ExternalBlob = Uint8Array;
export interface FlightDetails {
  'flightNumber' : string,
  'airline' : string,
  'confirmed' : boolean,
  'bookingPNR' : string,
}
export type Mode = { 'bus' : null } |
  { 'car' : null } |
  { 'train' : null } |
  { 'flight' : null } |
  { 'bike' : null };
export interface Parcel {
  'id' : bigint,
  'description' : string,
  'sender' : Principal,
  'travelMode' : Mode,
}
export interface Rating { 'user' : Principal, 'score' : number }
export interface TrainDetails {
  'pnr' : string,
  'verified' : boolean,
  'trainNumber' : string,
  'trainName' : string,
  'seatBerth' : string,
}
export interface Trip {
  'id' : bigint,
  'verified' : boolean,
  'details' : Conditional,
  'travelMode' : Mode,
  'carrier' : Principal,
}
export interface UserProfile {
  'governmentIdAddress' : [] | [string],
  'governmentIdUploaded' : boolean,
  'identityVerified' : boolean,
  'emailVerified' : boolean,
  'name' : string,
  'phoneNumber' : [] | [string],
  'phoneVerified' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNotif' : ActorMethod<[string], undefined>,
  'adminVerifyUserId' : ActorMethod<[Principal], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createParcel' : ActorMethod<[string, Mode], bigint>,
  'createTrip' : ActorMethod<[Conditional, Mode], bigint>,
  'deleteParcel' : ActorMethod<[bigint], undefined>,
  'deleteTrip' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getNotifications' : ActorMethod<[], Array<string>>,
  'getParcel' : ActorMethod<[bigint], [] | [Parcel]>,
  'getRatings' : ActorMethod<[Principal], Array<Rating>>,
  'getTrip' : ActorMethod<[bigint], [] | [Trip]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listParcels' : ActorMethod<[], Array<Parcel>>,
  'listTrips' : ActorMethod<[], Array<Trip>>,
  'markTripVerified' : ActorMethod<[bigint, boolean], undefined>,
  'mustBeAdmin' : ActorMethod<[], undefined>,
  'mustBeUser' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'signUp' : ActorMethod<[string, string, string], undefined>,
  'submitRating' : ActorMethod<[Principal, number], undefined>,
  'updateParcel' : ActorMethod<[bigint, string, Mode], undefined>,
  'updateTrip' : ActorMethod<[bigint, Conditional, Mode], undefined>,
  'uploadFrontIdScan' : ActorMethod<
    [ExternalBlob],
    { 'external' : ExternalBlob }
  >,
  'verifyEmail' : ActorMethod<[string], boolean>,
  'verifyMobileNumber' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];