/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Mode = IDL.Variant({
  'bus' : IDL.Null,
  'car' : IDL.Null,
  'train' : IDL.Null,
  'flight' : IDL.Null,
  'bike' : IDL.Null,
});
export const FlightDetails = IDL.Record({
  'flightNumber' : IDL.Text,
  'airline' : IDL.Text,
  'confirmed' : IDL.Bool,
  'bookingPNR' : IDL.Text,
});
export const BusDetails = IDL.Record({
  'verified' : IDL.Bool,
  'operator' : IDL.Text,
  'ticketReference' : IDL.Opt(IDL.Text),
  'seatNumber' : IDL.Nat,
});
export const CarDetails = IDL.Record({
  'verified' : IDL.Bool,
  'registration' : IDL.Text,
});
export const TrainDetails = IDL.Record({
  'pnr' : IDL.Text,
  'verified' : IDL.Bool,
  'trainNumber' : IDL.Text,
  'trainName' : IDL.Text,
  'seatBerth' : IDL.Text,
});
export const Conditional = IDL.Variant({
  'onFlight' : FlightDetails,
  'onBus' : BusDetails,
  'onCar' : CarDetails,
  'onTrain' : TrainDetails,
});
export const UserProfile = IDL.Record({
  'governmentIdAddress' : IDL.Opt(IDL.Text),
  'governmentIdUploaded' : IDL.Bool,
  'identityVerified' : IDL.Bool,
  'emailVerified' : IDL.Bool,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Opt(IDL.Text),
  'phoneVerified' : IDL.Bool,
});
export const Parcel = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'sender' : IDL.Principal,
  'travelMode' : Mode,
});
export const Rating = IDL.Record({
  'user' : IDL.Principal,
  'score' : IDL.Nat8,
});
export const Trip = IDL.Record({
  'id' : IDL.Nat,
  'verified' : IDL.Bool,
  'details' : Conditional,
  'travelMode' : Mode,
  'carrier' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNotif' : IDL.Func([IDL.Text], [], []),
  'adminVerifyUserId' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createParcel' : IDL.Func([IDL.Text, Mode], [IDL.Nat], []),
  'createTrip' : IDL.Func([Conditional, Mode], [IDL.Nat], []),
  'deleteParcel' : IDL.Func([IDL.Nat], [], []),
  'deleteTrip' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getParcel' : IDL.Func([IDL.Nat], [IDL.Opt(Parcel)], ['query']),
  'getRatings' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
  'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
  'listTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
  'markTripVerified' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'mustBeAdmin' : IDL.Func([], [], ['query']),
  'mustBeUser' : IDL.Func([], [], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'signUp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitRating' : IDL.Func([IDL.Principal, IDL.Nat8], [], []),
  'updateParcel' : IDL.Func([IDL.Nat, IDL.Text, Mode], [], []),
  'updateTrip' : IDL.Func([IDL.Nat, Conditional, Mode], [], []),
  'uploadFrontIdScan' : IDL.Func(
      [ExternalBlob],
      [IDL.Variant({ 'external' : ExternalBlob })],
      [],
    ),
  'verifyEmail' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'verifyMobileNumber' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Mode = IDL.Variant({
    'bus' : IDL.Null,
    'car' : IDL.Null,
    'train' : IDL.Null,
    'flight' : IDL.Null,
    'bike' : IDL.Null,
  });
  const FlightDetails = IDL.Record({
    'flightNumber' : IDL.Text,
    'airline' : IDL.Text,
    'confirmed' : IDL.Bool,
    'bookingPNR' : IDL.Text,
  });
  const BusDetails = IDL.Record({
    'verified' : IDL.Bool,
    'operator' : IDL.Text,
    'ticketReference' : IDL.Opt(IDL.Text),
    'seatNumber' : IDL.Nat,
  });
  const CarDetails = IDL.Record({
    'verified' : IDL.Bool,
    'registration' : IDL.Text,
  });
  const TrainDetails = IDL.Record({
    'pnr' : IDL.Text,
    'verified' : IDL.Bool,
    'trainNumber' : IDL.Text,
    'trainName' : IDL.Text,
    'seatBerth' : IDL.Text,
  });
  const Conditional = IDL.Variant({
    'onFlight' : FlightDetails,
    'onBus' : BusDetails,
    'onCar' : CarDetails,
    'onTrain' : TrainDetails,
  });
  const UserProfile = IDL.Record({
    'governmentIdAddress' : IDL.Opt(IDL.Text),
    'governmentIdUploaded' : IDL.Bool,
    'identityVerified' : IDL.Bool,
    'emailVerified' : IDL.Bool,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Opt(IDL.Text),
    'phoneVerified' : IDL.Bool,
  });
  const Parcel = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'sender' : IDL.Principal,
    'travelMode' : Mode,
  });
  const Rating = IDL.Record({ 'user' : IDL.Principal, 'score' : IDL.Nat8 });
  const Trip = IDL.Record({
    'id' : IDL.Nat,
    'verified' : IDL.Bool,
    'details' : Conditional,
    'travelMode' : Mode,
    'carrier' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNotif' : IDL.Func([IDL.Text], [], []),
    'adminVerifyUserId' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createParcel' : IDL.Func([IDL.Text, Mode], [IDL.Nat], []),
    'createTrip' : IDL.Func([Conditional, Mode], [IDL.Nat], []),
    'deleteParcel' : IDL.Func([IDL.Nat], [], []),
    'deleteTrip' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getParcel' : IDL.Func([IDL.Nat], [IDL.Opt(Parcel)], ['query']),
    'getRatings' : IDL.Func([IDL.Principal], [IDL.Vec(Rating)], ['query']),
    'getTrip' : IDL.Func([IDL.Nat], [IDL.Opt(Trip)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listParcels' : IDL.Func([], [IDL.Vec(Parcel)], ['query']),
    'listTrips' : IDL.Func([], [IDL.Vec(Trip)], ['query']),
    'markTripVerified' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'mustBeAdmin' : IDL.Func([], [], ['query']),
    'mustBeUser' : IDL.Func([], [], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'signUp' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitRating' : IDL.Func([IDL.Principal, IDL.Nat8], [], []),
    'updateParcel' : IDL.Func([IDL.Nat, IDL.Text, Mode], [], []),
    'updateTrip' : IDL.Func([IDL.Nat, Conditional, Mode], [], []),
    'uploadFrontIdScan' : IDL.Func(
        [ExternalBlob],
        [IDL.Variant({ 'external' : ExternalBlob })],
        [],
      ),
    'verifyEmail' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'verifyMobileNumber' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };