/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Trip {
    id: bigint;
    verified: boolean;
    details: Conditional;
    travelMode: Mode;
    carrier: Principal;
}
export interface Rating {
    user: Principal;
    score: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FlightDetails {
    flightNumber: string;
    airline: string;
    confirmed: boolean;
    bookingPNR: string;
}
export interface CarDetails {
    verified: boolean;
    registration: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BusDetails {
    verified: boolean;
    operator: string;
    ticketReference?: string;
    seatNumber: bigint;
}
export interface TrainDetails {
    pnr: string;
    verified: boolean;
    trainNumber: string;
    trainName: string;
    seatBerth: string;
}
export type Conditional = {
    __kind__: "onFlight";
    onFlight: FlightDetails;
} | {
    __kind__: "onBus";
    onBus: BusDetails;
} | {
    __kind__: "onCar";
    onCar: CarDetails;
} | {
    __kind__: "onTrain";
    onTrain: TrainDetails;
};
export interface Parcel {
    id: bigint;
    description: string;
    sender: Principal;
    travelMode: Mode;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    governmentIdAddress?: string;
    governmentIdUploaded: boolean;
    identityVerified: boolean;
    emailVerified: boolean;
    name: string;
    phoneNumber?: string;
    phoneVerified: boolean;
}
export enum Mode {
    bus = "bus",
    car = "car",
    train = "train",
    flight = "flight",
    bike = "bike"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addNotif(message: string): Promise<void>;
    adminVerifyUserId(user: Principal): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createParcel(desc: string, mode: Mode): Promise<bigint>;
    createTrip(details: Conditional, mode: Mode): Promise<bigint>;
    deleteParcel(id: bigint): Promise<void>;
    deleteTrip(id: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getNotifications(): Promise<Array<string>>;
    getParcel(id: bigint): Promise<Parcel | null>;
    getRatings(user: Principal): Promise<Array<Rating>>;
    getTrip(id: bigint): Promise<Trip | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listParcels(): Promise<Array<Parcel>>;
    listTrips(): Promise<Array<Trip>>;
    markTripVerified(id: bigint, verified: boolean): Promise<void>;
    mustBeAdmin(): Promise<void>;
    mustBeUser(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    signUp(name: string, phoneNumber: string, governmentIdAddress: string): Promise<void>;
    submitRating(user: Principal, score: number): Promise<void>;
    updateParcel(id: bigint, desc: string, mode: Mode): Promise<void>;
    updateTrip(id: bigint, details: Conditional, mode: Mode): Promise<void>;
    uploadFrontIdScan(blob: ExternalBlob): Promise<{
        __kind__: "external";
        external: ExternalBlob;
    }>;
    verifyEmail(otp: string): Promise<boolean>;
    verifyMobileNumber(otp: string): Promise<boolean>;
}
import type { BusDetails as _BusDetails, CarDetails as _CarDetails, Conditional as _Conditional, ExternalBlob as _ExternalBlob, FlightDetails as _FlightDetails, Mode as _Mode, Parcel as _Parcel, TrainDetails as _TrainDetails, Trip as _Trip, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addNotif(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotif(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotif(arg0);
            return result;
        }
    }
    async adminVerifyUserId(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminVerifyUserId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminVerifyUserId(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createParcel(arg0: string, arg1: Mode): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createParcel(arg0, to_candid_Mode_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createParcel(arg0, to_candid_Mode_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTrip(arg0: Conditional, arg1: Mode): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrip(to_candid_Conditional_n12(this._uploadFile, this._downloadFile, arg0), to_candid_Mode_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrip(to_candid_Conditional_n12(this._uploadFile, this._downloadFile, arg0), to_candid_Mode_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteParcel(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteParcel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteParcel(arg0);
            return result;
        }
    }
    async deleteTrip(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrip(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrip(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return result;
        }
    }
    async getParcel(arg0: bigint): Promise<Parcel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getParcel(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParcel(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatings(arg0: Principal): Promise<Array<Rating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatings(arg0);
            return result;
        }
    }
    async getTrip(arg0: bigint): Promise<Trip | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrip(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrip(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listParcels(): Promise<Array<Parcel>> {
        if (this.processError) {
            try {
                const result = await this.actor.listParcels();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listParcels();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrips(): Promise<Array<Trip>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrips();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrips();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async markTripVerified(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTripVerified(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTripVerified(arg0, arg1);
            return result;
        }
    }
    async mustBeAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.mustBeAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mustBeAdmin();
            return result;
        }
    }
    async mustBeUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.mustBeUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mustBeUser();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async signUp(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.signUp(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signUp(arg0, arg1, arg2);
            return result;
        }
    }
    async submitRating(arg0: Principal, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(arg0, arg1);
            return result;
        }
    }
    async updateParcel(arg0: bigint, arg1: string, arg2: Mode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParcel(arg0, arg1, to_candid_Mode_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParcel(arg0, arg1, to_candid_Mode_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateTrip(arg0: bigint, arg1: Conditional, arg2: Mode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrip(arg0, to_candid_Conditional_n12(this._uploadFile, this._downloadFile, arg1), to_candid_Mode_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrip(arg0, to_candid_Conditional_n12(this._uploadFile, this._downloadFile, arg1), to_candid_Mode_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async uploadFrontIdScan(arg0: ExternalBlob): Promise<{
        __kind__: "external";
        external: ExternalBlob;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFrontIdScan(await to_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFrontIdScan(await to_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyEmail(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEmail(arg0);
            return result;
        }
    }
    async verifyMobileNumber(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyMobileNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyMobileNumber(arg0);
            return result;
        }
    }
}
function from_candid_BusDetails_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BusDetails): BusDetails {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Conditional_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Conditional): Conditional {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Mode_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mode): Mode {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Parcel_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Parcel): Parcel {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Trip_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Trip): Trip {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Parcel]): Parcel | null {
    return value.length === 0 ? null : from_candid_Parcel_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Trip]): Trip | null {
    return value.length === 0 ? null : from_candid_Trip_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    governmentIdAddress: [] | [string];
    governmentIdUploaded: boolean;
    identityVerified: boolean;
    emailVerified: boolean;
    name: string;
    phoneNumber: [] | [string];
    phoneVerified: boolean;
}): {
    governmentIdAddress?: string;
    governmentIdUploaded: boolean;
    identityVerified: boolean;
    emailVerified: boolean;
    name: string;
    phoneNumber?: string;
    phoneVerified: boolean;
} {
    return {
        governmentIdAddress: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.governmentIdAddress)),
        governmentIdUploaded: value.governmentIdUploaded,
        identityVerified: value.identityVerified,
        emailVerified: value.emailVerified,
        name: value.name,
        phoneNumber: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.phoneNumber)),
        phoneVerified: value.phoneVerified
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    description: string;
    sender: Principal;
    travelMode: _Mode;
}): {
    id: bigint;
    description: string;
    sender: Principal;
    travelMode: Mode;
} {
    return {
        id: value.id,
        description: value.description,
        sender: value.sender,
        travelMode: from_candid_Mode_n25(_uploadFile, _downloadFile, value.travelMode)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    verified: boolean;
    details: _Conditional;
    travelMode: _Mode;
    carrier: Principal;
}): {
    id: bigint;
    verified: boolean;
    details: Conditional;
    travelMode: Mode;
    carrier: Principal;
} {
    return {
        id: value.id,
        verified: value.verified,
        details: from_candid_Conditional_n30(_uploadFile, _downloadFile, value.details),
        travelMode: from_candid_Mode_n25(_uploadFile, _downloadFile, value.travelMode),
        carrier: value.carrier
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: boolean;
    operator: string;
    ticketReference: [] | [string];
    seatNumber: bigint;
}): {
    verified: boolean;
    operator: string;
    ticketReference?: string;
    seatNumber: bigint;
} {
    return {
        verified: value.verified,
        operator: value.operator,
        ticketReference: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.ticketReference)),
        seatNumber: value.seatNumber
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bus: null;
} | {
    car: null;
} | {
    train: null;
} | {
    flight: null;
} | {
    bike: null;
}): Mode {
    return "bus" in value ? Mode.bus : "car" in value ? Mode.car : "train" in value ? Mode.train : "flight" in value ? Mode.flight : "bike" in value ? Mode.bike : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onFlight: _FlightDetails;
} | {
    onBus: _BusDetails;
} | {
    onCar: _CarDetails;
} | {
    onTrain: _TrainDetails;
}): {
    __kind__: "onFlight";
    onFlight: FlightDetails;
} | {
    __kind__: "onBus";
    onBus: BusDetails;
} | {
    __kind__: "onCar";
    onCar: CarDetails;
} | {
    __kind__: "onTrain";
    onTrain: TrainDetails;
} {
    return "onFlight" in value ? {
        __kind__: "onFlight",
        onFlight: value.onFlight
    } : "onBus" in value ? {
        __kind__: "onBus",
        onBus: from_candid_BusDetails_n32(_uploadFile, _downloadFile, value.onBus)
    } : "onCar" in value ? {
        __kind__: "onCar",
        onCar: value.onCar
    } : "onTrain" in value ? {
        __kind__: "onTrain",
        onTrain: value.onTrain
    } : value;
}
async function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    external: _ExternalBlob;
}): Promise<{
    __kind__: "external";
    external: ExternalBlob;
}> {
    return "external" in value ? {
        __kind__: "external",
        external: await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value.external)
    } : value;
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Parcel>): Array<Parcel> {
    return value.map((x)=>from_candid_Parcel_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Trip>): Array<Trip> {
    return value.map((x)=>from_candid_Trip_n28(_uploadFile, _downloadFile, x));
}
function to_candid_BusDetails_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BusDetails): _BusDetails {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Conditional_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Conditional): _Conditional {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Mode_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): _Mode {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: boolean;
    operator: string;
    ticketReference?: string;
    seatNumber: bigint;
}): {
    verified: boolean;
    operator: string;
    ticketReference: [] | [string];
    seatNumber: bigint;
} {
    return {
        verified: value.verified,
        operator: value.operator,
        ticketReference: value.ticketReference ? candid_some(value.ticketReference) : candid_none(),
        seatNumber: value.seatNumber
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    governmentIdAddress?: string;
    governmentIdUploaded: boolean;
    identityVerified: boolean;
    emailVerified: boolean;
    name: string;
    phoneNumber?: string;
    phoneVerified: boolean;
}): {
    governmentIdAddress: [] | [string];
    governmentIdUploaded: boolean;
    identityVerified: boolean;
    emailVerified: boolean;
    name: string;
    phoneNumber: [] | [string];
    phoneVerified: boolean;
} {
    return {
        governmentIdAddress: value.governmentIdAddress ? candid_some(value.governmentIdAddress) : candid_none(),
        governmentIdUploaded: value.governmentIdUploaded,
        identityVerified: value.identityVerified,
        emailVerified: value.emailVerified,
        name: value.name,
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none(),
        phoneVerified: value.phoneVerified
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mode): {
    bus: null;
} | {
    car: null;
} | {
    train: null;
} | {
    flight: null;
} | {
    bike: null;
} {
    return value == Mode.bus ? {
        bus: null
    } : value == Mode.car ? {
        car: null
    } : value == Mode.train ? {
        train: null
    } : value == Mode.flight ? {
        flight: null
    } : value == Mode.bike ? {
        bike: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "onFlight";
    onFlight: FlightDetails;
} | {
    __kind__: "onBus";
    onBus: BusDetails;
} | {
    __kind__: "onCar";
    onCar: CarDetails;
} | {
    __kind__: "onTrain";
    onTrain: TrainDetails;
}): {
    onFlight: _FlightDetails;
} | {
    onBus: _BusDetails;
} | {
    onCar: _CarDetails;
} | {
    onTrain: _TrainDetails;
} {
    return value.__kind__ === "onFlight" ? {
        onFlight: value.onFlight
    } : value.__kind__ === "onBus" ? {
        onBus: to_candid_BusDetails_n14(_uploadFile, _downloadFile, value.onBus)
    } : value.__kind__ === "onCar" ? {
        onCar: value.onCar
    } : value.__kind__ === "onTrain" ? {
        onTrain: value.onTrain
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
